services:
  issuer_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    volumes:
      - /tmp/issuer_frontend/log_dev:/tmp/issuer_frontend/log_dev
      - /etc/issuer_config/frontend_config.yaml:/etc/issuer_config/frontend_config.yaml:ro
    restart: unless-stopped
